[package]
name = "orx-concurrent-option"
version = "0.1.0"
edition = "2021"
publish = ["artifactory"]

[dependencies]


[dev-dependencies]
test-case = "3.3.1"


[features]
default = []
experimental = []
